### ISSUE TITLE
Undefined symbols for architecture armv7:   "_UnityGetMetalBundle"

### ISSUE THREAD

**Issue by roffiel** [RatioInnovacion/Wink-Toolbox#9]
Al hacer una app con vuforia 3.0.9 y MMT 2.0.4 hay un **Apple Mach-O-Linker Error**:

´´´
Undefined symbols for architecture armv7:
  "_UnityGetMetalBundle", referenced from:
      +[TextureMetal aClassMethod:height:] in libtheorawrapper.a(TextureMetal.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
´´´

**Comment by RaschidGithub** [comment]
Se arregló actualizando a Vuforia 5 y Unity 5.

**Comment by wwwang89** [comment]
yeah ，except update my unity to version 5.0 ，any else solutions？thanks~~
